### ISSUE TITLE
Hydrogen Run fails

### ISSUE THREAD

**Issue by filgto2000** [lgeiger/hydrogen-launcher#35]
**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: Microsoft Windows 10 Education
**Thrown From**: [greyatom-hydrogen](https://github.com/greyatom-edu-tech/greyatom-hydrogen) package 1.9.0

### Stack Trace

Uncaught TypeError: this.editor.languageMode.rowRangeForCodeFoldAtBufferRow is not a function

```
At C:\Users\Fil\.atom\packages\greyatom-hydrogen\lib\code-manager.js:37

TypeError: this.editor.languageMode.rowRangeForCodeFoldAtBufferRow is not a function
    at CodeManager.findCodeBlock (/packages/greyatom-hydrogen/lib/code-manager.js:37:48)
    at Object.run (/packages/greyatom-hydrogen/lib/main.js:358:40)
    at HTMLElement.hydrogenRun (/packages/greyatom-hydrogen/lib/main.js:55:34)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:349858)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:1231210)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:1227344)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:285037)
```

### Commands

```
     -0:11.4.0 intentions:highlight (input.hidden-input)
     -0:10.4.0 hydrogen:run (input.hidden-input)
```

### Non-Core Packages

```
greyatom-hydrogen 1.9.0 
Hydrogen 2.6.0 
hydrogen-launcher 1.2.2 
hydrogen-xdbg 0.0.4 
intentions 1.1.5 
kite 0.123.0 
linter 2.2.0 
minimap 4.29.9 
```

**Comment by wadethestealth** [comment]
Your issue is a greyatom-hydrogen issue. This doesn't relate to hydrogen launcher, and you should close this issue and open one at greyatom-hydrogen.
