### ISSUE TITLE
Failed to load the hydrogen-launcher package

### ISSUE THREAD

**Issue by nishigandha24** [lgeiger/hydrogen-launcher#42]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [hydrogen-launcher](https://github.com/lgeiger/hydrogen-launcher) package 1.2.2

### Stack Trace

Failed to load the hydrogen-launcher package

```
At Cannot find module 'term-launcher'
Require stack:
- C:\Users\hp\.atom\packages\hydrogen-launcher-master\lib\main.js
- C:\Users\hp\AppData\Local\atom\app-1.47.0\resources\app.asar\static\index.html

Error: Cannot find module 'term-launcher'
Require stack:
- C:\Users\hp\.atom\packages\hydrogen-launcher-master\lib\main.js
- C:\Users\hp\AppData\Local\atom\app-1.47.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.47.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:155434)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:146766)
    at /packages/hydrogen-launcher-master/lib/main.js:7:21)
    at /packages/hydrogen-launcher-master/lib/main.js:158:32)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:1:735013)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3310163)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3296703
    at Package.measure (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3295535)
    at Package.load (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3296276)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:381312)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:379735
    at Config.transact (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:331800)
    at PackageManager.loadPackages (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:379673)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:1:755624
    at async Promise.all (index 0)
    at AtomEnvironment.startEditorWindow (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:1:757663)
```

### Commands

```
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
hydrogen-cell-separator 0.4.1 
hydrogen-launcher 1.2.2 
hydrogen-python 0.0.8 
```

**Comment by tvertver** [comment]
Hydrogen App not starting
Mac OSx: 10.13.6
Hydrogen version 1.2.2

Hydrogen 1.2.2 [Sep 9 2023] [http://www.hydrogen-music.org]
Copyright 2002-2008 Alessandro Cominu
Copyright 2008-2023 The hydrogen development team
Hydrogen comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it under certain conditions. See the file COPYING for details.
(E) XMLDoc::read Unable to read conversion result document [/Users/macbook/Library/Application Support/Hydrogen/hydrogen.conf]
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
Referenced from: /Applications/Open Source and More/Hydrogen-1.2.2/Hydrogen 1.2.2.app/Contents/MacOS/../Frameworks/libpcre2-16.0.dylib (which was built for Mac OS X 10.15)
Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
Referenced from: /Applications/Open Source and More/Hydrogen-1.2.2/Hydrogen 1.2.2.app/Contents/MacOS/../Frameworks/libpcre2-16.0.dylib (which was built for Mac OS X 10.15)
Expected in: /usr/lib/libSystem.B.dylib

Fatal error in: Initialising Hydrogen
(E) ::void handleFatalSignal(int) Fatal signal 6
(E) ::void handleFatalSignal(int) 0 hydrogen 0x000000010e982e1d _ZN6H2Core4Base12count_activeEv + 2109
(E) ::void handleFatalSignal(int) 1 libsystem_platform.dylib 0x00007fff629f8f5a _sigtramp + 26
(E) ::void handleFatalSignal(int) 2 ??? 0x0000000117b1c50b 0x0 + 4692493579
(E) ::void handleFatalSignal(int) 3 ??? 0x0000000117b26bf5 0x0 + 4692536309
(E) ::void handleFatalSignal(int) 4 ??? 0x0000000117afa482 0x0 + 4692354178
(E) ::void handleFatalSignal(int) 5 ??? 0x0000000117afa5a9 0x0 + 4692354473
(E) ::void handleFatalSignal(int) 6 libdyld.dylib 0x00007fff626ea292 dyld_stub_binder + 282
(E) ::void handleFatalSignal(int) 7 libpcre2-16.0.dylib 0x00000001106700c0 pcre2_substring_number_from_name_16 + 152303
(E) ::void handleFatalSignal(int) 8 QtCore 0x0000000110111003 _ZN18QRegularExpressionC1ER25QRegularExpressionPrivate + 787
(E) ::void handleFatalSignal(int) 9 QtCore 0x00000001101125f9 _ZNK18QRegularExpression5matchERK7QStringiNS_9MatchTypeE6QFlagsINS_11MatchOptionEE + 41
(E) ::void handleFatalSignal(int) 10 QtXml 0x000000010efcf1dd _ZNK8QDomNode10isDocumentEv + 317
(E) ::void handleFatalSignal(int) 11 QtXml 0x000000010efda478 _ZNK12QDomDocument8toStringEi + 88
(E) ::void handleFatalSignal(int) 12 hydrogen 0x000000010eaaa06f _ZN6H2Core6XMLDoc5writeERK7QString + 719
(E) ::void handleFatalSignal(int) 13 hydrogen 0x000000010eb42b47 _ZN6H2Core11Preferences15savePreferencesEv + 23015
(E) ::void handleFatalSignal(int) 14 hydrogen 0x000000010eb3bafa _ZN6H2Core11Preferences15loadPreferencesEb + 51082
(E) ::void handleFatalSignal(int) 15 hydrogen 0x000000010eb2eac6 _ZN6H2Core11PreferencesC2Ev + 6342
(E) ::void handleFatalSignal(int) 16 hydrogen 0x000000010eb2d1f5 _ZN6H2Core11PreferencesC1Ev + 21
(E) ::void handleFatalSignal(int) 17 hydrogen 0x000000010eb2d196 _ZN6H2Core11Preferences15create_instanceEv + 54
(E) ::void handleFatalSignal(int) 18 hydrogen 0x000000010e97ee9c main + 8636
(E) ::void handleFatalSignal(int) 19 libdyld.dylib 0x00007fff626ea015 start + 1
(E) ::void handleFatalSignal(int) 20 ??? 0x0000000000000002 0x0 + 2

Log File:
�[31m(E) XMLDoc::read Unable to read conversion result document [/Users/macbook/Library/Application Support/Hydrogen/hydrogen.conf]�[0m
�[31m(E) ::void handleFatalSignal(int) Fatal signal 6�[0m
�[31m(E) ::void handleFatalSignal(int) 0 hydrogen 0x000000010fa38e1d _ZN6H2Core4Base12count_activeEv + 2109�[0m
�[31m(E) ::void handleFatalSignal(int) 1 libsystem_platform.dylib 0x00007fff629f8f5a _sigtramp + 26�[0m
�[31m(E) ::void handleFatalSignal(int) 2 ??? 0x000000011b9c750b 0x0 + 4758205707�[0m
�[31m(E) ::void handleFatalSignal(int) 3 ??? 0x000000011b9d1bf5 0x0 + 4758248437�[0m
�[31m(E) ::void handleFatalSignal(int) 4 ??? 0x000000011b9a5482 0x0 + 4758066306�[0m
�[31m(E) ::void handleFatalSignal(int) 5 ??? 0x000000011b9a55a9 0x0 + 4758066601�[0m
�[31m(E) ::void handleFatalSignal(int) 6 libdyld.dylib 0x00007fff626ea292 dyld_stub_binder + 282�[0m
�[31m(E) ::void handleFatalSignal(int) 7 libpcre2-16.0.dylib 0x00000001117380c0 pcre2_substring_number_from_name_16 + 152303�[0m
�[31m(E) ::void handleFatalSignal(int) 8 QtCore 0x00000001111d4003 _ZN18QRegularExpressionC1ER25QRegularExpressionPrivate + 787�[0m
�[31m(E) ::void handleFatalSignal(int) 9 QtCore 0x00000001111d55f9 _ZNK18QRegularExpression5matchERK7QStringiNS_9MatchTypeE6QFlagsINS_11MatchOptionEE + 41�[0m
�[31m(E) ::void handleFatalSignal(int) 10 QtXml 0x000000011008e1dd _ZNK8QDomNode10isDocumentEv + 317�[0m
�[31m(E) ::void handleFatalSignal(int) 11 QtXml 0x0000000110099478 _ZNK12QDomDocument8toStringEi + 88�[0m
�[31m(E) ::void handleFatalSignal(int) 12 hydrogen 0x000000010fb6006f _ZN6H2Core6XMLDoc5writeERK7QString + 719�[0m
�[31m(E) ::void handleFatalSignal(int) 13 hydrogen 0x000000010fbf8b47 _ZN6H2Core11Preferences15savePreferencesEv + 23015�[0m
�[31m(E) ::void handleFatalSignal(int) 14 hydrogen 0x000000010fbf1afa _ZN6H2Core11Preferences15loadPreferencesEb + 51082�[0m
�[31m(E) ::void handleFatalSignal(int) 15 hydrogen 0x000000010fbe4ac6 _ZN6H2Core11PreferencesC2Ev + 6342�[0m
�[31m(E) ::void handleFatalSignal(int) 16 hydrogen 0x000000010fbe31f5 _ZN6H2Core11PreferencesC1Ev + 21�[0m
�[31m(E) ::void handleFatalSignal(int) 17 hydrogen 0x000000010fbe3196 _ZN6H2Core11Preferences15create_instanceEv + 54�[0m
�[31m(E) ::void handleFatalSignal(int) 18 hydrogen 0x000000010fa34e9c main + 8636�[0m
�[31m(E) ::void handleFatalSignal(int) 19 libdyld.dylib 0x00007fff626ea015 start + 1�[0m
�[31m(E) ::void handleFatalSignal(int) 20 ??? 0x0000000000000002 0x0 + 2�[0m
Stop logger
<img width="650" alt="Screen Shot 2023-12-26 at 7 58 39 AM" src="https://github.com/lgeiger/hydrogen-launcher/assets/154909102/e851b598-95d5-4ad8-be05-f376dfa00631">
